// ── Organización ─────────────────────────────────────────────────────────────

export const SEDES = ["Sede Principal", "Sede 3 / Cruz Roja"];

export const AREAS = [
  "FACTURACION", "CARTERA", "COMPRAS", "AUDITORIA EXTERNA", "TALENTO HUMANO",
  "CONTRATACIONES", "JURIDICA", "CALIDAD", "CUENTAS MEDICAS", "CONSULTA EXTERNA",
  "FARMACIA", "SISTEMA", "BLOQUE DE ENFERMERIA", "MANTENIMIENTO", "ALMACEN",
  "UCI ADULTO", "UCI NEONATAL", "UCI INTERMEDIA", "HOSPITALIZACION",
  "FACTURACION HOSPITALIZACION", "NUTRICION", "CIRUGIA", "RADIOLOGIA",
  "URGENCIA OBSERVACION PEDIATRICA", "OBSERVACION PEDIATRICA", "URGENCIA OBS ADULTO",
  "ESTAR ENFERMERIA 1", "REANIMACION", "COORDINACION URGENCIA", "URGENCIA EVOLUCION",
  "SALA TRANSITORIA", "SALA DE TERAPIA RESPIRATORIA", "TRIAGE 1", "TRIAGE 2",
  "CUARTO DE INTERNOS", "CONSULTORIO 2 URGENCIA", "CONSULTORIO 4 URGENCIA",
  "CONSULTORIO 5 URGENCIA", "CONSULTORIO 6 URGENCIA", "FACTCABINA URGENCIA",
  "ADMISIONES URGENCIA", "OFICINA DOCENCIA Y SERVICIO", "BIBLIOTECA", "SIMULACION",
  "SALA DE USUARIOS", "SALON 21H1", "SALON 21H2", "SALON 22H2", "SALON 23H1",
  "SALON 24H2", "SALON 25H2", "SALON 26H2", "SALON 28H2", "INVESTIGACION",
  "ADMISION CONSULTA EXTERNA", "FACTURACION SEDE 3", "PSICOLOGIA", "PATOLOGIA",
  "GESTION AL USUARIO", "TRABAJO SOCIAL", "ODONTOLOGIA", "FACTURACION ODONTOLOGIA",
  "VACUNACION", "ADMINISTRACION ODONTOLOGIA", "CALL CENTER", "SIAU",
  "CIRUGIA COORDINACION", "PROGRAMACION DE CIRUGIA Y FACTURACION", "LABORATORIO",
  "AUTORIZACIONES", "SISTEMAS", "AUDITORIA INTERNA", "TESORERIA", "CONTABILIDAD",
  "ENFERMERIA CONSULTA EXTERNA", "COORDINACION DE ENFERMERIA", "ENDOSCOPIA 1",
  "ENDOSCOPIA 2", "MATERNIDAD", "FARMACIA DE CIRUGIA", "RECUPERACION DE CIRUGIA",
  "GESTION DOCUMENTAL", "CONSULTORIO JURIDICO", "TICS", "ADMINISTRACION FINANCIERA",
  "DIRECCION ADMINISTRATIVA", "ADMINISTRACION", "DIRECCION MEDICA",
  "SUBDIRECCION DE INTERNACION", "UNIVOLUNTARIOS", "CAJA 1", "CAJA 2",
  "COORDINADOR DU NORD H", "HEMODINAMIA", "RADIOLOGIA CUARTO TECNICO",
  "RADIOLOGIA SALA DE LECTURA", "HOLTER", "CARDIOSOF", "CIRUGIA ESTERILIZACION",
  "SERVICIOS GENERALES", "ENFERMERIA URGENCIA", "CONTROL DE MONITOREO",
  "URGENCIA", "BODEGA SISTEMAS", "CENTRAL DE MONITOREO", "CENTRAL DE MONITOREO UCI INT",
  "SST", "CONSULTORIO 1 URGENCIA", "CONSULTORIO 3 URGENCIA", "CONSULTORIO 7 URGENCIA",
];

export const UBICACION = [
  "OFICINA DE FACTURACION", "OFICINA DE CARTERA", "OFICINA DE COMPRAS",
  "OFICINA AUDITORIA EXTERNA", "OFICINA DE TALENTO HUMANO",
  "OFICINA COMERCIAL Y CONTRATACIONES", "OFICINA JURIDICA", "OFICINA DE CALIDAD",
  "OFICINA DE CUENTAS MEDICAS", "FISIOTERAPIA", "FARMACIA", "FARMACIA BODEGA",
  "FARMACIA CONSIGNACION", "FARMACIA PRINCIPAL", "TIC", "BLOQUE E", "MANTENIMIENTO",
  "ALMACEN", "UCI ADULTO", "UCI NEONATAL", "UCI INTERMEDIA", "HOSPITALIZACION",
  "OFICINA DE NUTRICION", "COORDINACION CIRUGIA", "RADIOLOGIA",
  "OBSERVACION PEDIATRICA", "FARMACIA URGENCIA", "ESTAR 1", "REANIMACION",
  "COORDINACION URGENCIAS", "EVOLUCION", "SALA TRANSITORIA", "TERAPIA RESPIRATORIA",
  "TRIAGE 1", "TRIAGE 2", "CONSULTORIO 2", "CONSULTORIO 4", "CONSULTORIO 5",
  "CONSULTORIO 6", "FACTURACION URGENCIAS", "ADMISIONES URGENCIAS",
  "BLOQUE ACADEMICO", "CENTRO DE INVESTIGACION CLINICA", "CONSULTA EXTERNA",
  "ADMISION CONSULTA EXTERNA", "PSICOLOGIA", "PATOLOGIA",
  "RECEPCION ATENCION AL USUARIO", "TRABAJO SOCIAL", "ODONTOLOGIA", "CALL CENTER",
  "CIRUGIA", "LABORATORIO CLINICO", "AUTORIZACIONES", "AUDITORIA INTERNA",
  "OFICINA DE TESORERIA", "OFICINA DE CONTABILIDAD", "URGENCIAS", "CONSULTORIO 1",
  "CONSULTORIO 3", "CONSULTORIO 7", "CONSULTORIA DE PROCEDIMIENTO", "ENDOSCOPIA 1",
  "ENDOSCOPIA 2", "MATERNIDAD", "FARMACIA CIRUGIA", "RECUPERACION CIRUGIA",
  "GESTION DOCUMENTAL", "VENTANILLA", "SEDE 3", "RACK ODONTOLOGIA",
  "DIRECCION ADMINISTRATIVA Y FINANCIERA", "ADMINISTRACION", "COSTOS",
  "ASISTENTE DIRECCION EJECUTIVA", "OFICINA DIRECTOR CIENTIFICO",
  "OFICINA UNIVOLUNTARIOS", "CAJA 1", "CAJA 2", "COORDINADOR DU NORD H",
  "SERVICIOS GENERALES", "ESTAR DE ENFERMERIA", "CENTRAL DE MONITOREO",
  "CONSULTORIO ECOGRAFIA", "BODEGA TIC", "RACK SERVIDORES",
];

export const PROCESO = [
  "FACTURACION", "CARTERA", "GESTION RECURSOS MATERIALES",
  "GESTION DE OPERACIONES ASISTENCIALES", "GESTION DEL TALENTO HUMANO",
  "GESTION JURIDICA", "GESTION DE CALIDAD", "CONSULTA EXTERNA", "INVESTIGACION",
  "FARMACIA", "GESTION DE TIC", "HOSPITALIZACION", "DIRECCIONAMIENTO ESTRATEGICO",
  "URGENCIAS", "AUDITORIA MEDICA", "GESTION DE INFRAESTRUCTURA", "UCI ADULTO",
  "UCI NEONATAL", "CIRUGIA Y MATERNIDAD", "IMAGENES DIAGNOSTICAS", "DOCENCIA SERVICIO",
  "LABORATORIO CLINICO Y PATOLOGIA", "SIAU", "ODONTOLOGIA", "CONTROL INTERNO",
  "TESORERIA", "CONTABILIDAD", "GESTION DOCUMENTAL Y ARCHIVO", "HOTELERIA",
  "GESTION DE LA TECNOLOGIA BIOMEDICA", "SST",
];

export const CENTRO_COSTO = [
  "ADMINISTRACION HOSPITAL", "GESTION DE OPERACIONES", "DIRECCIONAMIENTO", "CALIDAD",
  "CONSULTA EXTERNA", "CENTRO INVESTIGACION CLINICA", "FARMACIA", "UCI ADULTO",
  "URGENCIAS", "HOSPITALIZACION PISO 1", "HOSPITALIZACION PISO 2", "UCI NEONATAL",
  "CIRUGIA", "CONVENIO DOCENTE ASISTENCIAL", "LABORATORIO", "ATENCION AL USUARIO",
  "CLINICA ODONTOLOGICA", "DU NORD H",
];

export const PISOS = ["1", "2"];
export const TIPO_PROCESO = ["MISIONAL", "APOYO", "ESTRATEGICO"];

// ── Equipo ───────────────────────────────────────────────────────────────────

export const ENTIDAD_PROPIETARIO = ["SONDA", "HUN", "UNINORTE", "NUEVA EPS", "TECHNOMEDICAL", "REGISTRADURIA", "N/A"];
export const TIPOS_EQUIPO = ["Desktop", "Laptop", "All-in-One", "Servidor", "Otro"];
export const ESTADO = ["NO-EXT", "Ok", "N/A", "Apagado"];

export const TIPO_DISCO = [
  "Solido", "Solido NVMe", "Mecanico", "Rotacional",
  "MSA2040 (Rotacional)", "MSA2060 (Solido)", "N/A",
];

// ── Software ─────────────────────────────────────────────────────────────────

export const OFFICE = [
  "2010", "2013", "2016", "2019", "2019 PRO", "2021", "365", "OPEN OFFICE", "N/A",
];

export const ANTIVIRUS = [
  "BITDEFENDER", "Cortex", "TREND MICRO", "SYMANTEC", "MCAFEE", "Trellix", "N/A",
];

// ── Estado inicial del formulario ─────────────────────────────────────────────

export const EMPTY = {
  // Organización
  fecha: "", sede: "", area: "", ubicacion: "", tipoProceso: "", proceso: "",
  centroCosto: "", piso: "",
  // Identificación
  equipo: "", activo: "", usuario: "", usuarioResponsable: "",
  dominio: "", so: "", entidadPropietario: "",
  // Hardware
  marca: "", modelo: "", tipoEquipo: "", serial: "",
  cpu: "", coresHilos: "", memoria: "",
  discoResumen: "", monitorResumen: "", activoMonitor: "", ramResumen: "",
  // Red
  ip: "", mascaraRed: "", gateway: "", mac: "", wirelessMac: "", etiquetaPuntoRed: "",
  // Observaciones
  observaciones: "",
  // Datos del .txt (estructurados)
  netAdapters: [], discos: [], memorias: [], monitor: null, apps: [],
};